# Global properties
separator=false
markup=pango

[terminal]
full_text=  
color=#807dfe
command=i3-msg -q exec alacritty

[browser]
full_text= 
color=#ff7f81
command=i3-msg -q exec brave

[files]
full_text= 
color=#7f3fbf
command=i3-msg -q exec android-file-transfer

[Bluetooth]
full_text=  
color=#7f3fbf
command=i3-msg -q exec blueman-manager

separator=true

[network]
label=  
command=~/.config/i3/i3blocks/network.sh
interval=20
color=#61afef

separator=true

[memory]
label=  
command=~/.config/i3/i3blocks/memory.sh
interval=5
color=#9aedfe

separator=true

[Audio]
full_text=
color=#7f3fbf
command=i3-msg -q exec pavucontrol

[time]
command=date '+%a %d %b %H:%M:%S'
interval=1
color=#ffffff
